FROM oven/bun:1

WORKDIR /usr/src/app

COPY package.json bun.lock ./

RUN bun install

COPY . .


RUN bunx turbo build --filter=backend...
RUN bun run generate:db

EXPOSE 8080

CMD ["bun", "start:backend"]